spring:
  application:
    name: category-catalog
    
  config:
    import: optional:configserver:http://localhost:8888
    
  profiles:
    active:
    - test
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/eshop-prod
          #jwk-set-uri: http://localhost:8080/auth/realms/eshop-prod/protocol/open
