name: CI/CD Pipeline for Product-Catalog

on:
  push:
    paths:
      - 'product-catalog/**'
  pull_request:
    paths:
      - 'product-catalog/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Pull mongo docker image
      run: docker pull mongodb/mongodb-community-server:7.0.11-ubuntu2204

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '7.0.11'

    - name: Build and test product-catalog
      working-directory: product-catalog
      run: mvn clean verify -Dspring.profiles.active=test

    - name: Archive Test Reports for product-catalog
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: product-catalog-test-reports
        path: product-catalog/target/surefire-reports/

    - name: Archive Integration Test Reports for product-catalog
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: product-catalog-integration-test-reports
        path: product-catalog/target/failsafe-reports/

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images for product-catalog
      run: |
        docker build -t devforreal/product-catalog:latest ./product-catalog
        docker push devforreal/product-catalog:latest
